-- MySQL Script generated by MySQL Workbench
-- Wed May 14 10:29:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`region` (
  `region_id` INT NOT NULL AUTO_INCREMENT,
  `region_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  `region_region_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_region_idx` (`region_region_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_region`
    FOREIGN KEY (`region_region_id`)
    REFERENCES `pizzeria`.`region` (`region_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(45) NOT NULL,
  `client_surname` VARCHAR(45) NOT NULL,
  `client_address` VARCHAR(45) NULL,
  `client_zip_code` VARCHAR(45) NULL,
  `client_phone` VARCHAR(45) NOT NULL,
  `city_city_id` INT NOT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `fk_client_city1_idx` (`city_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `pizzeria`.`city` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`shop` (
  `shop_id` INT NOT NULL AUTO_INCREMENT,
  `shop_address` VARCHAR(45) NOT NULL,
  `shop_zip_code` VARCHAR(45) NOT NULL,
  `city_city_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`),
  INDEX `fk_shop_city1_idx` (`city_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_shop_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `pizzeria`.`city` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_surname` VARCHAR(45) NOT NULL,
  `employee_id_num` VARCHAR(45) NOT NULL,
  `employee_phone` VARCHAR(45) NOT NULL,
  `employee_position` ENUM("delivery", "cook") NOT NULL,
  `shop_shop_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_employee_shop1_idx` (`shop_shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_shop1`
    FOREIGN KEY (`shop_shop_id`)
    REFERENCES `pizzeria`.`shop` (`shop_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `order_type` ENUM("restaurant", "take_away") NOT NULL,
  `order_price` DECIMAL(10,2) NOT NULL,
  `client_client_id` INT NOT NULL,
  `employee_employee_id` INT NOT NULL,
  `shop_shop_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_client1_idx` (`client_client_id` ASC) VISIBLE,
  INDEX `fk_order_employee1_idx` (`employee_employee_id` ASC) VISIBLE,
  INDEX `fk_order_shop1_idx` (`shop_shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_client1`
    FOREIGN KEY (`client_client_id`)
    REFERENCES `pizzeria`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_employee1`
    FOREIGN KEY (`employee_employee_id`)
    REFERENCES `pizzeria`.`employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_shop1`
    FOREIGN KEY (`shop_shop_id`)
    REFERENCES `pizzeria`.`shop` (`shop_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizza_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizza_category` (
  `pizza_category_id` INT NOT NULL AUTO_INCREMENT,
  `pizza_category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pizza_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`products` (
  `products_id` INT NOT NULL AUTO_INCREMENT,
  `products_name` VARCHAR(45) NOT NULL,
  `products_description` VARCHAR(45) NOT NULL,
  `products_picture` BLOB NOT NULL,
  `products_price` DECIMAL(10,2) NOT NULL,
  `products_type` ENUM("pizzas", "burguers", "drinks") NOT NULL,
  `pizza_category_pizza_category_id` INT NULL,
  PRIMARY KEY (`products_id`),
  INDEX `fk_product_pizza_cathegory1_idx` (`pizza_category_pizza_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_pizza_cathegory1`
    FOREIGN KEY (`pizza_category_pizza_category_id`)
    REFERENCES `pizzeria`.`pizza_category` (`pizza_category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`order_uniques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`order_uniques` (
  `order_uniques_id` INT NOT NULL AUTO_INCREMENT,
  `order_uniques_amount` INT NOT NULL,
  `order_uniques_price` DECIMAL(10,2) NOT NULL,
  `products_products_id` INT NOT NULL,
  `order_order_id` INT NOT NULL,
  PRIMARY KEY (`order_uniques_id`),
  INDEX `fk_order_uniques_products1_idx` (`products_products_id` ASC) VISIBLE,
  INDEX `fk_order_uniques_order1_idx` (`order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_uniques_products1`
    FOREIGN KEY (`products_products_id`)
    REFERENCES `pizzeria`.`products` (`products_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_uniques_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `pizzeria`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
