-- MySQL Script generated by MySQL Workbench
-- Wed May 14 10:28:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optic_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optic_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optic_shop` DEFAULT CHARACTER SET utf8 ;
USE `optic_shop` ;

-- -----------------------------------------------------
-- Table `optic_shop`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optic_shop`.`addresses` (
  `addresses_id` INT NOT NULL,
  `addresses_street` VARCHAR(45) NOT NULL,
  `addresses_street_num` VARCHAR(45) NOT NULL,
  `addresses_floor` VARCHAR(45) NULL DEFAULT NULL,
  `addresses_door` VARCHAR(45) NULL DEFAULT NULL,
  `addresses_city` VARCHAR(45) NOT NULL,
  `addresses_zip` VARCHAR(45) NOT NULL,
  `addresses_country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`addresses_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optic_shop`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optic_shop`.`suppliers` (
  `suppliers_id` INT NOT NULL AUTO_INCREMENT,
  `suppliers_name` VARCHAR(45) NOT NULL,
  `suppliers_phone` VARCHAR(45) NOT NULL,
  `suppliers_fax` VARCHAR(45) NULL,
  `suppliers_fiscal_id` VARCHAR(45) NOT NULL,
  `addresses_addresses_id` INT NOT NULL,
  PRIMARY KEY (`suppliers_id`, `addresses_addresses_id`),
  INDEX `fk_suppliers_addresses1_idx` (`addresses_addresses_id` ASC) VISIBLE,
  CONSTRAINT `fk_suppliers_addresses1`
    FOREIGN KEY (`addresses_addresses_id`)
    REFERENCES `optic_shop`.`addresses` (`addresses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optic_shop`.`recomended_by`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optic_shop`.`recomended_by` (
  `recomended_by_id` INT NOT NULL AUTO_INCREMENT,
  `recomended_by_client_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recomended_by_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optic_shop`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optic_shop`.`clients` (
  `clients_id` INT NOT NULL,
  `clients_first_name` VARCHAR(45) NOT NULL,
  `clients_last_name` VARCHAR(45) NOT NULL,
  `clients_phone` VARCHAR(45) NOT NULL,
  `clients_email` VARCHAR(45) NOT NULL,
  `clients_creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `addresses_addresses_id` INT NOT NULL,
  `recomended_by_recomended_by_id` INT NOT NULL,
  PRIMARY KEY (`clients_id`, `addresses_addresses_id`),
  INDEX `fk_clients_addresses1_idx` (`addresses_addresses_id` ASC) VISIBLE,
  INDEX `fk_clients_recomended_by1_idx` (`recomended_by_recomended_by_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_addresses1`
    FOREIGN KEY (`addresses_addresses_id`)
    REFERENCES `optic_shop`.`addresses` (`addresses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_clients_recomended_by1`
    FOREIGN KEY (`recomended_by_recomended_by_id`)
    REFERENCES `optic_shop`.`recomended_by` (`recomended_by_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optic_shop`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optic_shop`.`brands` (
  `brands_id` INT NOT NULL AUTO_INCREMENT,
  `brands_name` VARCHAR(45) NOT NULL,
  `suppliers_suppliers_id` INT NOT NULL,
  PRIMARY KEY (`brands_id`),
  INDEX `fk_brands_suppliers1_idx` (`suppliers_suppliers_id` ASC) VISIBLE,
  CONSTRAINT `fk_brands_suppliers1`
    FOREIGN KEY (`suppliers_suppliers_id`)
    REFERENCES `optic_shop`.`suppliers` (`suppliers_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optic_shop`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optic_shop`.`glasses` (
  `glasses_id` INT NOT NULL,
  `glasses_prescription` DECIMAL(4,2) NOT NULL,
  `glasses_frame` ENUM("M", "P", "F") NOT NULL,
  `glasses_frame_color` VARCHAR(45) NOT NULL,
  `glasses_lens_color_left` VARCHAR(45) NOT NULL,
  `glasses_lens_color_right` VARCHAR(45) NOT NULL,
  `glasses_price` DECIMAL(6,2) NOT NULL,
  `brands_brands_id` INT NOT NULL,
  PRIMARY KEY (`glasses_id`),
  INDEX `fk_glasses_brands1_idx` (`brands_brands_id` ASC) VISIBLE,
  CONSTRAINT `fk_glasses_brands1`
    FOREIGN KEY (`brands_brands_id`)
    REFERENCES `optic_shop`.`brands` (`brands_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optic_shop`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optic_shop`.`employees` (
  `employees_id` INT NOT NULL AUTO_INCREMENT,
  `employees_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employees_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optic_shop`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optic_shop`.`sales` (
  `sales_id` INT NOT NULL,
  `sales_total` DECIMAL(7,2) NOT NULL,
  `sales_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `clients_clients_id` INT NOT NULL,
  `employees_employees_id` INT NOT NULL,
  PRIMARY KEY (`sales_id`),
  INDEX `fk_sales_clients1_idx` (`clients_clients_id` ASC) VISIBLE,
  INDEX `fk_sales_employees1_idx` (`employees_employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_clients1`
    FOREIGN KEY (`clients_clients_id`)
    REFERENCES `optic_shop`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_employees1`
    FOREIGN KEY (`employees_employees_id`)
    REFERENCES `optic_shop`.`employees` (`employees_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optic_shop`.`sales_has_glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optic_shop`.`sales_has_glasses` (
  `sales_has_glasses_id` INT NOT NULL,
  `glasses_glasses_id` INT NOT NULL,
  `sales_sales_id` INT NOT NULL,
  PRIMARY KEY (`sales_has_glasses_id`, `glasses_glasses_id`, `sales_sales_id`),
  INDEX `fk_sales_has_glasses_glasses_idx` (`glasses_glasses_id` ASC) VISIBLE,
  INDEX `fk_sales_has_glasses_sales1_idx` (`sales_sales_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_has_glasses_glasses`
    FOREIGN KEY (`glasses_glasses_id`)
    REFERENCES `optic_shop`.`glasses` (`glasses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_has_glasses_sales1`
    FOREIGN KEY (`sales_sales_id`)
    REFERENCES `optic_shop`.`sales` (`sales_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
